# [START cloud_tasks_app_yaml]
runtime: nodejs12

# [START cloud_tasks_app_env_vars]
env_variables:
  PROJECT_ID: "sacc-team-a"
  QUEUE_ID: "default"
  QUEUE_LOCATION: "europe-west1"
# [END cloud_tasks_app_env_vars]

# [END cloud_tasks_app_yaml]
