# [START cloud_tasks_app_yaml]
runtime: nodejs12

## [START cloud_tasks_app_env_vars]
env_variables:
  PROJECT_ID: "sacc-team-a"
  QUEUE_ID: "default"
  QUEUE_LOCATION: "europe-west1"
## [END cloud_tasks_app_env_vars]

## [START scaling_app_env_vars]
automatic_scaling:
  target_cpu_utilization: 0.50
  min_instances: 1
  max_instances: 5
  min_pending_latency: 30ms
  max_pending_latency: automatic
  max_concurrent_requests: 2
## [END scaling_app_env_vars]

# [END cloud_tasks_app_yaml]

# [START gae_pubsub_yaml]
env_variables:
  PUBSUB_TOPIC: YOUR_TOPIC_NAME
  # This token is used to verify that requests originate from your
  # application. It can be any sufficiently random string.
  PUBSUB_VERIFICATION_TOKEN: YOUR_VERIFICATION_TOKEN
# [END gae_pubsub_yaml]